//BUBBLE SORT
export const BUBBLE_SORT = "BUBBLE_SORT";
export const SWAP_COL_BUBBLE = "SWAP_COL_BUBBLE";
export const CURRENT_BUBBLE_COL = "CURRENT_BUBBLE_COL";
export const LOW_SPEED_SORT = "LOW_SPEED_SORT";
